### ISSUE TITLE
Wrong Following Total Count

### ISSUE THREAD

**Issue by davidmelvin** [gbrammer/liberate-spotify#2]
Hi! Thank you very much for this script. I'm trying to use it to move my Followed artists from one account to another. I have a question that I don't think is a bug of your script, but maybe you can help me understand what's going on?

I'm following 1,455 accounts (I assume a combo of artists and normal users, but mostly artists) but the Spotify following endpoint returns 203 as the "total" in the returned result. Do you know why this might be? It happens in the API explorer as well.

**Comment by gbrammer** [comment]
Thanks for your message @davidmelvin.  It's been so long since I looked at this I'm not sure what was causing the problem, but I hope you were able to figure it out!
